DROP TABLE IF EXISTS index_info CASCADE;
DROP TABLE IF EXISTS index_data CASCADE;
DROP TABLE IF EXISTS sync_job CASCADE;
DROP TABLE IF EXISTS auto_sync_config CASCADE;

CREATE TABLE IF NOT EXISTS index_info
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_classification VARCHAR(255)   NOT NULL,
    index_name           VARCHAR(100)   NOT NULL,
    employed_items_count INTEGER        NOT NULL,
    base_point_in_time   DATE           NOT NULL,
    base_index           INTEGER        NOT NULL,
    source_type          VARCHAR(10)    NOT NULL,
    favorite             BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_index UNIQUE (index_classification, index_name)
);

CREATE TABLE IF NOT EXISTS index_data
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_info_id       BIGINT      NOT NULL,
    base_date           DATE        NOT NULL,
    source_type         VARCHAR(10) NOT NULL CHECK (source_type IN ('USER', 'OPEN_API')),
    market_price        NUMERIC(20, 2),
    closing_price       NUMERIC(20, 2),
    high_price          NUMERIC(20, 1),
    low_price           NUMERIC(20, 1),
    versus              NUMERIC(20, 1),
    fluctuation_rate    NUMERIC(20, 1),
    trading_quantity    BIGINT,
    trading_price       BIGINT,
    market_total_amount BIGINT,
    CONSTRAINT uk_index_date UNIQUE (index_info_id, base_date),
    CONSTRAINT fk_index_data_info FOREIGN KEY (index_info_id) REFERENCES index_info (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sync_job
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_info_id BIGINT       NOT NULL,
    job_type      VARCHAR(10)  NOT NULL,
    target_date   DATE         NOT NULL,
    worker        VARCHAR(100) NOT NULL,
    job_time      TIMESTAMP    NOT NULL,
    result        VARCHAR(10)  NOT NULL,
    CONSTRAINT fk_sync_job_info FOREIGN KEY (index_info_id) REFERENCES index_info (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS auto_sync_config
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_info_id BIGINT UNIQUE NOT NULL,
    enabled       BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_auto_sync_info FOREIGN KEY (index_info_id) REFERENCES index_info (id) ON DELETE CASCADE
);

CREATE INDEX idx_index_info_index_classification ON index_info (index_classification);
CREATE INDEX idx_index_info_index_name ON index_info (index_name);

CREATE INDEX idx_index_data_info_date_id ON index_data (index_info_id, base_date, id);
CREATE INDEX idx_index_data_info_closing_id ON index_data (index_info_id, closing_price, id);

CREATE INDEX idx_sync_job_target_date ON sync_job (target_date);
CREATE INDEX idx_sync_jbo_job_time ON sync_job (job_time);